import mongoose from "mongoose";

import {
  deleteUploadedDocuments,
  uploadDocuments,
} from "../../common/services/document-upload.service.js";
import Client from "../models/client.model.js";
import ClientCompany from "../models/clientCompany.model.js";
import ClientDocument from "../models/clientDocuments.model.js";
import ClientDriver from "../models/clientDrivers.model.js";
import ClientMember from "../models/clientMembers.model.js";
import ClientPayment from "../models/clientPayment.model.js";
import ClientReminder from "../models/clientReminder.model.js";
import ClientService from "../models/clientService.model.js";
import ClientVehicle from "../models/clientVehicles.model.js";

// Creates one document through Mongoose's array form so the active transaction session is honored.
// This helper keeps single-record creation consistent for the Client and optional Company records.
const createOneRecord = async (Model, payload, session) => {
  const [record] = await Model.create([payload], { session });
  return record;
};

// Adds the server-owned Client reference to every related payload before inserting the records.
// Empty or omitted sections return an empty array without issuing an unnecessary database call.
const createRelatedRecords = async (Model, records, clientId, session) => {
  if (!records?.length) {
    return [];
  }

  return Model.create(
    records.map((record) => ({ ...record, client: clientId })),
    { session }
  );
};

// Combines uploaded Cloudinary locations with optional metadata in the same positional order as files.
// URL and Client reference values are generated by the server and cannot be supplied by the caller.
const buildDocumentRecords = (files, uploads, metadata, clientId) =>
  uploads.map((upload, index) => ({
    ...(metadata?.[index] ?? {}),
    client: clientId,
    documentTitle: metadata?.[index]?.documentTitle ?? files[index].originalname,
    documentType: metadata?.[index]?.documentType ?? "Other",
    documentURL: upload.documentUrl,
    cloudinaryPublicId: upload.publicId,
    cloudinaryResourceType: upload.resourceType,
  }));

// Creates the Client and all requested related records in one MongoDB transaction after uploads finish.
// Failed persistence removes uploaded files, while failed uploads never begin a database transaction.
export const createClientAggregate = async (
  payload,
  files,
  correlationId
) => {
  let uploads = [];
  let session;
  let result;

  try {
    uploads = await uploadDocuments(files, correlationId);
    session = await mongoose.startSession();

    await session.withTransaction(async () => {
      const client = await createOneRecord(Client, payload.client, session);
      const company = payload.company
        ? await createOneRecord(
            ClientCompany,
            { ...payload.company, client: client._id },
            session
          )
        : null;
      const members = await createRelatedRecords(
        ClientMember,
        payload.members,
        client._id,
        session
      );
      const vehicles = await createRelatedRecords(
        ClientVehicle,
        payload.vehicles,
        client._id,
        session
      );
      const drivers = await createRelatedRecords(
        ClientDriver,
        payload.drivers,
        client._id,
        session
      );
      const services = await createRelatedRecords(
        ClientService,
        payload.services,
        client._id,
        session
      );
      const documents = uploads.length
        ? await ClientDocument.create(
            buildDocumentRecords(
              files,
              uploads,
              payload.documents,
              client._id
            ),
            { session }
          )
        : [];
      const payments = await createRelatedRecords(
        ClientPayment,
        payload.payments,
        client._id,
        session
      );
      const reminders = await createRelatedRecords(
        ClientReminder,
        payload.reminders,
        client._id,
        session
      );

      result = {
        client,
        company,
        members,
        vehicles,
        drivers,
        services,
        documents,
        payments,
        reminders,
      };
    });

    return result;
  } catch (error) {
    await deleteUploadedDocuments(uploads);
    throw error;
  } finally {
    if (session) {
      await session.endSession();
    }
  }
};
